b:
	cargo build

sort-all:
	cargo test -- sorting

comb-sort:
	cargo test -- test_comb_sort

gnome-sort:
	cargo test -- test_gnome

odd-even-sort:
	cargo test -- test_odd_even_sort

radix-sort:
	cargo test -- test_radix_sort

selection-sort:
	cargo test -- test_selection_sort

shell-sort:
	cargo test -- test_shell_sort

stooge-sort:
	cargo test -- test_stooge_sort

search:
	cargo test -- searching

data-stru:
	cargo test -- data_structures

linked-list:
	cargo test -- test_linked_list

b-tree:
	cargo test -- test_b_tree

graph:
	cargo test -- graph

heap:
	cargo test -- heap

queue:
	cargo test -- queue

doc:
	cargo doc
